---
galaxy:
  rules:
    - if: $CI_COMMIT_TAG != null
  script:
    - ansible-galaxy role import --api-key ${GALAXY_API_KEY} buluma ${CI_PROJECT_NAME}
image: buluma/github-action-molecule:5.1.1
molecule:
  allow_failure: true
  parallel:
    matrix:
      - image: amazonlinux
        tag: latest
      - image: debian-systemd
        tag: bullseye
      - image: enterpriselinux
        tag: "7"
      - image: enterpriselinux
        tag: "8"
      - image: enterpriselinux
        tag: latest
      - image: fedora-systemd
        tag: "37"
      - image: fedora-systemd
        tag: "38"
      - image: docker-ubuntu-systemd
        tag: latest
      - image: docker-ubuntu-systemd
        tag: focal
      - image: docker-ubuntu-systemd
        tag: lunar
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
  script:
    - molecule test
variables:
  PY_COLORS: 1
